
name: Ubuntu LXDE via Chrome Remote Desktop

on:
  workflow_dispatch:

jobs:
  chrome-remote-desktop:
    runs-on: ubuntu-latest
    env:
      CRD_HEADLESS_CODE: ${{ secrets.CRD_HEADLESS_CODE }}
      CRD_REDIRECT_URL: ${{ secrets.CRD_REDIRECT_URL }}
      CRD_HOSTNAME: github-runner
      CRD_PIN: 123456789

    steps:
      - name: Install LXDE & prerequisites
        run: |
          sudo apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive \
            apt-get install -y \
              lxde-core \
              wget \
              dbus-x11 \
              xvfb \
              sudo

      - name: Create user “mehraz”
        run: |
          sudo useradd -m -s /bin/bash mehraz
          echo "mehraz:123456789" | sudo chpasswd
          sudo usermod -aG sudo mehraz

      - name: Install Chrome Remote Desktop Host
        run: |
          wget -O /tmp/crd.deb \
            https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt install -y /tmp/crd.deb
          sudo apt-get install -f -y

      - name: Start virtual X server on :0
        run: |
          # starts Xvfb in the background on :0 so CRD can open a Gtk window
          Xvfb :0 -screen 0 1920x1080x24 &
          sleep 5

      - name: Register & start CRD host
        run: |
          # feed the PIN twice into the headless registration
          printf '%s\n' "$CRD_PIN" "$CRD_PIN" | \
            sudo -u mehraz \
            DISPLAY=:0 \
            /opt/google/chrome-remote-desktop/chrome-remote-desktop-host \
              --code="$CRD_HEADLESS_CODE" \
              --redirect-url="$CRD_REDIRECT_URL" \
              --name="$CRD_HOSTNAME"

          # enable and start the systemd service so it picks up the new config
          sudo systemctl enable --now chrome-remote-desktop@mehraz

      - name: Keep the runner alive
        run: sleep infinity
        
