# .github/workflows/windows11-rdp-tailscale.yml
name: Windows 11 Pro RDP via Tailscale

on:
  workflow_dispatch:

jobs:
  rdp-via-tailscale:
    runs-on: windows-latest
    timeout-minutes: 1440
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

    steps:
      - name: Create user “mehraz9” with complex password
        shell: cmd
        run: |
          net user mehraz9 "Mehraz@990088!" /add /passwordchg:no /expires:never
          net localgroup Administrators mehraz9 /add

      - name: Enable Windows Remote Desktop
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' `
            -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download and install Tailscale
        shell: powershell
        run: |
          # Correct stable URL for Windows installer
          $url = "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe"
          $out = "$env:RUNNER_TEMP\tailscale-setup.exe"
          Invoke-WebRequest -Uri $url -OutFile $out
          Start-Process $out -ArgumentList "/quiet" -Wait
          Start-Service Tailscale

      - name: Authenticate & bring up Tailscale
        shell: powershell
        run: |
          tailscale up `
            --authkey $Env:TAILSCALE_AUTHKEY `
            --hostname github-windows11 `
            --accept-routes `
            --accept-dns

      - name: Show your Tailscale IP
        shell: powershell
        run: |
          $ip = tailscale ip -4
          Write-Host "Connect your RDP client to: $ip"

      - name: Keep session alive for 24 hours
        shell: powershell
        run: Start-Sleep -Seconds 86400
        
